version: '3.7'

services:

    postgres:
        image: postgres
        container_name: "postgres"
        ports:
            - 5432:5432
        environment:
            POSTGRES_PASSWORD: 123
        volumes:
            - postgres_data:/var/lib/postgresql/data

    pgadmin:
        image: dpage/pgadmin4
        container_name: pgadmin
        ports:
            - 5050:80
        environment:
            PGADMIN_DEFAULT_EMAIL: postgres@host.docker.internal
            PGADMIN_DEFAULT_PASSWORD: 123


volumes:
    postgres_data:
